
pipeline {
    agent any
    stages {
        stage('Create kubernetes cluster') {
            steps {
                withAWS(region:'us-west-2', credentials:'aws-devops') {
                    sh '''
                    eksctl create cluster \
                    --name capstone-cloud-devops-cluster \
                    --version 1.16 \
                    --nodegroup-name standard-workers \
                    --node-type t2.micro \
                    --nodes 2 \
                    --nodes-min 1 \
                    --nodes-max 3 \
                    --node-ami auto \
                    --region us-west-2
                    '''
                }
            }
        }
    }
}